### ISSUE TITLE
Sasslint doesn't support BEM

### ISSUE THREAD

**Issue by plumpNation** [itslearning/protomorph#12]
Error message is `[sass-lint] Class '.prom-modal__button' should be written in lowercase with hyphens (class-name-format)`.

We shouldn't enforce only hyphens, teams should be able to use BEM. The lowercase thing I do agree with.

**Comment by EsmeraldiBejolli** [comment]
Settings  from sass linter

`convention: hyphenatedbem`

When enabled, the following are allowed:

```
.site-search {
  color: blue;
  width: 50px;
  height: 100%;
}

.site-search__field {
  text-decoration: underline;
}

.site-search--full {
  color: green;
}
```

**When enabled, the following are disallowed:**

```
.HYPHENATED-UPPERCASE {
  content: '';
}

.foo {
  @extend .camelCase;
}
```

**Comment by furstenberg** [comment]
This has already been resolved.
