### ISSUE TITLE
babel does not support Async/await

### ISSUE THREAD

**Issue by EsmeraldiBejolli** [itslearning/protomorph#14]
async/await is not supported by babel transpiler it seems to be very old

**Comment by plumpNation** [comment]
The babel core engine is 7.0.0-beta.46, as shown in the package.json, and the babel loader is 8.0.0-beta.0.

I don't think the babel dependencies are very old, maybe it just needs https://babeljs.io/docs/plugins/syntax-async-functions/ or a preset like https://babeljs.io/docs/plugins/preset-es2015/.

One thing I am concerned about is slamming presets into the protomorph config without knowing exactly what it is that is going in and why. That means if presets are going in, we should understand each and every plugin that is contained in that preset before it is committed.

**Comment by EsmeraldiBejolli** [comment]
@plumpNation you are right we might not need to add polyfils for IE to support async/await since is not so relevant to have them.
I suggest to keep bundle package as light as possible.
Since we have Promises I do not see any benefit to support async/await at the moment.

so please feel free to close this issue.
