### ISSUE TITLE
The build should not delete folders from the node_modules

### ISSUE THREAD

**Issue by plumpNation** [itslearning/protomorph#16]
The "clean" plugin that runs before a build deletes build folders.

It should only delete the folders in the project consuming protomorph.

To replicate, simply `yarn build` and read the initial output.

```
clean-webpack-plugin: /Volumes/Workspace/repos/prometheus/dist has been removed.
clean-webpack-plugin: /Volumes/Workspace/repos/prometheus/node_modules/@itslearning/protomorph/dist has been removed.
clean-webpack-plugin: /Volumes/Workspace/repos/prometheus/node_modules/@itslearning/protomorph/build has been removed.
```

**Comment by furstenberg** [comment]
Yeah I see this as well. Strange.

**Comment by furstenberg** [comment]
Is this still an issue? 

cc: @alex-irt @stephane-vanraes

**Comment by alex-irt** [comment]
This is still an issue
