### ISSUE TITLE
Investigate serialize-javascript

### ISSUE THREAD

**Issue by furstenberg** [itslearning/protomorph#59]

**Comment by alex-irt** [comment]
Packages that depend on the serialize-javascript with a security alert:

- Hoisted from "copy-webpack-plugin#serialize-javascript"
- Hoisted from "rollup-plugin-terser#serialize-javascript"
- Hoisted from "webpack#terser-webpack-plugin#serialize-javascript"

rollup-plugin-terser MR: https://github.com/TrySound/rollup-plugin-terser/pull/53
